### ISSUE TITLE
"Safe" way to use this library given the warning about arbitrary Python code

### ISSUE THREAD

**Issue by d3f2** [ccurme/yolopandas#29]
What's the relatively "safe" way to use this library to isolate it from user data on my machine? Would using it inside a docker container be ok or do I have to go further and only use it on a machine with a fresh install of os-x? I am responding to the "Warning: YOLOPandas will execute arbitrary Python code on the machine it runs on. This is a dangerous thing to do." I have browsed the code looks ok.

**Comment by ccurme** [comment]
I'd recommend running inside a Docker container.
